# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
- stage: Pruebas
  displayName: Pruebas

  jobs:
    # track deployments on the environment
    - deployment: DeployWeb
      displayName: deploy Web App
      pool:
        vmImage: ubuntu-latest
      # creates an environment if it doesn't exist
      environment:
        name: 'Pruebas'
      variables:
        name: 'Deployment::Pruebas'
      strategy:
        # default deployment strategy, more coming...
        runOnce:
          deploy:
            steps:
            - script: echo my first deployment
